# Generated by Django 4.2.1 on 2023-05-31 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task', models.TextField()),
                ('created', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
